name: direct_drawing_generator
description: Direct Drawing Generator Flutter application inspired by the K-OS-ERI design.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.2
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  collection: ^1.18.0
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/reference/
